### PR TITLE
Adds onSubmit to forms that are missing it

### PR DESCRIPTION
**Pull request by megoth**
I've added onSubmit handling (and removed the existing onClick handling) for

- Create folder
- Managing existing access for an agent

There is a form that I haven't fixed yet, because I'm waiting for a fix in the Solid UI React. I'll create a separate PR for it later.

I also checked the following forms, which was already fixed:

- Pod Navigator
- Adding new contact

- [x] I've added a unit test to test for potential regressions of this bug.
- [ ] The changelog has been updated, if applicable.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

### CODE REVIEW

**Review by VirginiaBalseiro — CHANGES_REQUESTED** [review]
When I try creating a new folder, the form only submits when I press enter, not when I click on the button.

**Comment by megoth** [comment]
> When I try creating a new folder, the form only submits when I press enter, not when I click on the button.

Ooof, that's embarassing. But turns out that adding `type="submit"` to Material UI Button does not do the trick, and there's no apparent work-around except putting a normal button inside an `IconButton`. So I opted for switching button and input field into Prism button and input, which makes it more coherent with other forms.

**Comment by VirginiaBalseiro** [comment]
> > When I try creating a new folder, the form only submits when I press enter, not when I click on the button.
> 
> Ooof, that's embarassing. But turns out that adding `type="submit"` to Material UI Button does not do the trick, and there's no apparent work-around except putting a normal button inside an `IconButton`. So I opted for switching button and input field into Prism button and input, which makes it more coherent with other forms.

Still not working for me. I thought Vercel's Preview might have not updated so I checked out the branch and ran it locally and it's still not submitting on click.

**Comment by megoth** [comment]
> Still not working for me. I thought Vercel's Preview might have not updated so I checked out the branch and ran it locally and it's still not submitting on click.

Ok, this is not my day, forgot to actually change type on button in last commit... Thought I'd tested, but obviously went a bit faster than I should've. Apologies. It should be fixed now.

**Review by VirginiaBalseiro — APPROVED** [review]

**Review by kevin-inrupt — CHANGES_REQUESTED** [review]
QA issues.

**Review by kevin-inrupt — APPROVED** [review]

**Pull request merged**
