### PR TITLE
chore: upgrade sentry to ^6.18.1

### PR DESCRIPTION
**Pull request by ThisIsMissEm**
## Description

This could/should fix an error that was happening on page loads where there was a 4xx error requesting a resource — I don't entirely understand the bug, but I'm pretty sure it was coming from Sentry: https://twitter.com/thisismissem/status/1499144570994663425?s=21

## Changes

Upgraded Sentry to 6.18.1

## Testing

Tested in vercel

## Commit checklist

- [x] All acceptance criteria are met.
- [x] Includes tests to ensure functionality and prevent regressions.
- [x] Relevant documentation, if any, has been written/updated.
- [x] The changelog has been updated, if applicable.

## Interested parties

@inrupt/apps-developers

### CODE REVIEW

**Comment by ThisIsMissEm** [comment]
Related: https://github.com/inrupt/pod-browser/pull/447

**Review by solid-akb — APPROVED** [review]
Do we need to make any changes to Sentry config in tandem with this PR?

**Comment by ThisIsMissEm** [comment]
> Do we need to make any changes to Sentry config in tandem with this PR?

Honestly, I don't know — but as it's all a 6.x.y line, it should not have breaking changes (and the sentry team are usually pretty good at following semver)

**Review by daytonn — APPROVED** [review]
Thank you :pray:

**Review by daytonn — APPROVED** [review]

**Pull request merged**
