### PR TITLE
Showing a prominent warning if user don't have Control access to Pod

### PR DESCRIPTION
**Pull request by megoth**
# New feature description

Added a new warning that shows a warning if user for some reason don't have Control access to their own Pod.

bilde

Relies on changes in https://github.com/inrupt/prism/pull/126.

# Checklist

- [x] All acceptance criteria are met.
- [ ] Relevant documentation, if any, has been written/updated.
- [ ] The changelog has been updated, if applicable.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

# How to test

Don't add Control access when authenticating with a NSS-based account. Alternatively remove Control access from an existing entry in Trusted Apps.

### CODE REVIEW

**Comment by VirginiaBalseiro** [comment]
There is an error:
```

Unhandled error during request: TypeError: Cannot read property 'substring' of undefined
--
at getContainerUrl (/vercel/workpath0/.next/serverless/pages/resource/[iri].js:1892:14)

```
that is preventing the Vercel Preview from building.

**Comment by VirginiaBalseiro** [comment]
When I do grant Control access the message is briefly displayed when first loading the Files view, when logging out and when navigating to and from the Files view. Occasionally also a "Could not load your pod" message is shown before this warning when logging in.

**Comment by megoth** [comment]
> When I log in with ESS the message is briefly displayed when first loading the Files view, when logging out and when navigating to and from the Files view. Occasionally also a "Could not load your pod" message is shown before this warning when logging in. This does not happen when logging in with NSS and granting Control access.

I've fixed this in the most recent commit, so please re-review.

The error was that I initiated the ACP Strategy a bit to early, before `policiesContainer` was loaded/created properly. This in turn threw an error, which triggered a condition that showed the NoControlWarning component. Should be fixed now  ^_^

**Comment by megoth** [comment]
> When I log in with ESS the message is briefly displayed when first loading the Files view, when logging out and when navigating to and from the Files view. Occasionally also a "Could not load your pod" message is shown before this warning when logging in. This does not happen when logging in with NSS and granting Control access.

I've fixed this in the most recent commit, so please re-review.

The error was that I initiated the ACP Strategy a bit to early, before `policiesContainer` was loaded/created properly. This in turn threw an error, which triggered a condition that showed the NoControlWarning component. Should be fixed now  ^_^

**Review by VirginiaBalseiro — APPROVED** [review]

**Comment by kevin-inrupt** [comment]
Tested the Vercel preview and only get the app read, write, and append permission (i.e., no control) to the inrupt.net Pod.
```
            [
                n1:mode n1:Append, n1:Read, n1:Write;
                n1:origin
                    <https://pod-browser-git-fix-show-no-control-error.inrupt.vercel.app>
            ];
```

No warning message is not displayed, and if I attempt to the context menu for a resource, the cursor just spins - no errors are shown in the console.

**Review by kevin-inrupt — CHANGES_REQUESTED** [review]
See my comment in the conversation.

**Comment by megoth** [comment]
> See my comment in the conversation.

Should be fixed in latest PRs; I'll ask @VirginiaBalseiro to re-review as well.

**Review by kevin-inrupt — APPROVED** [review]
From a functionality perspective, the warning is working, **_although_** it it could be improved if the warning is displayed quicker.

**Comment by megoth** [comment]
> From a functionality perspective, the warning is working, **_although_** it it could be improved if the warning is displayed quicker.

The slowness of the warning is because we need to do a sequence of requests before we can *know* for certain whether the warning should be shown or not.

One way to mitigate this is to not show the table initially until we know for sure. We can cache the response so that all subsequent tests will be instantenous. But this means that the initial table will take about as long as you wait now until it is shown.

Let's discuss whether we want to do this or not in the upcoming standup.

**Pull request merged**
