### PR TITLE
Chore: update readme

### PR DESCRIPTION
**Pull request by VirginiaBalseiro**
- removing unnecessary section
- updating installation instructions
- adding badges
- adding Inrupt logo and updating header section text
- adding links

### CODE REVIEW

**Review by KyraAssaad — APPROVED** [review]
Yay 👏🏽 👏🏽 👏🏽

**Review by ajacksified — COMMENTED** [review]
Stars, forks, and watchers seems like a bit of duplication without much useful information.

Do the PRs and Issues badges change color based on how many are open?

**Review by solid-akb — APPROVED** [review]
Looks awesome!

**Comment by KyraAssaad** [comment]
> Stars, forks, and watchers seems like a bit of duplication without much useful information.
> 
> Do the PRs and Issues badges change color based on how many are open?

Doesn't look like they change color, based on the examples provided here: https://shields.io/category/issue-tracking

We could remove the stars, forks and watchers. The other ones are duplicates too but they look kinda nice 😁

**Review by ajacksified — APPROVED** [review]

**Pull request merged**
